lib/lucidboard_web/router.ex
defmodule LucidboardWeb.Router do
  use LucidboardWeb, :router
  alias LucidboardWeb.LayoutView

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(Phoenix.LiveView.Flash)
    plug(LucidboardWeb.LoadUserPlug)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:put_layout, {LayoutView, :normal})
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/auth", LucidboardWeb do
    pipe_through([:browser])

    get("/:provider", AuthController, :request)
    get("/:provider/callback", AuthController, :callback)
  end

  scope "/", LucidboardWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/changelog", PageController, :changelog)

    get("/signin", UserController, :signin)
    post("/signin", AuthController, :dumb_signin)
    get("/signout", AuthController, :signout)

    get("/user-settings", UserController, :settings)
    post("/user-settings", UserController, :update_settings)

    live("/dashboard", DashboardLive, session: [:user_id])
    live("/create-board", CreateBoardLive, session: [:path_params, :user_id])

    live("/boards", DashboardLive, session: [:user_id])
    live("/boards/:id", BoardLive, session: [:path_params, :user_id])

    post("/boards/:id/dnd-into-junction", BoardController, :dnd_into_junction)
    post("/boards/:id/dnd-into-pile", BoardController, :dnd_into_pile)
  end
end

lib/lucidboard_web/live/dashboard_live.ex
defmodule LucidboardWeb.DashboardLive do
  @moduledoc "The LiveView for the dashboard page"
  use Phoenix.LiveView
  alias Lucidboard.{ShortBoard, Twiddler}
  alias LucidboardWeb.{DashboardView, Endpoint}
  alias LucidboardWeb.Router.Helpers, as: Routes

  def render(assigns) do
    DashboardView.render("index.html", assigns)
  end

  def mount(%{user_id: nil}, socket) do
    socket =
      socket
      |> put_flash(:error, "You must be signed in")
      |> redirect(to: Routes.user_path(Endpoint, :signin))

    {:stop, socket}
  end

  def mount(%{user_id: user_id}, socket) do
    Lucidboard.subscribe("dashboards")

    socket =
      socket
      |> assign(
        user_id: user_id,
        subscriptions: MapSet.new(),
        boards_filter: "all"
      )
      |> load_data_and_handle_subscriptions()

    {:ok, socket}
  end

  def handle_info(:full_reload, socket) do
    {:noreply, load_data_and_handle_subscriptions(socket)}
  end

  def handle_info({:short_board, short_board}, socket) do
    short_boards =
      socket.assigns.short_boards
      |> Enum.find_index(fn sb -> sb.id == short_board.id end)
      |> case do
        nil -> socket.assigns.short_boards
        idx -> List.replace_at(socket.assigns.short_boards, idx, short_board)
      end

    {:noreply, assign(socket, :short_boards, short_boards)}
  end

  def handle_event(
        "search",
        %{"q" => search_key, "boards_filter" => boards_filter},
        socket
      ) do
    {:noreply,
     load_data_and_handle_subscriptions(socket, 0, search_key, boards_filter)}
  end

  def handle_event("paginate", direction, socket) do
    socket =
      load_data_and_handle_subscriptions(
        socket,
        if(direction == "prev", do: -1, else: 1),
        socket.assigns.search_key,
        socket.assigns.boards_filter
      )

    {:noreply, socket}
  end

  # Loads all dashboard data and updates subscriptions to reflect the visible
  # boards.
  defp load_data_and_handle_subscriptions(
         socket,
         page_direction \\ 0,
         q \\ nil,
         boards_filter \\ nil
       ) do
    search_key = q || socket.assigns[:search_key]
    boards_filter = boards_filter || socket.assigns[:boards_filter]

    board_pagination =
      Twiddler.boards(
        socket.assigns.user_id,
        (get_page_number(socket) || 1) + page_direction,
        search_key,
        boards_filter
      )

    short_boards = Enum.map(board_pagination, &ShortBoard.from_board/1)
    new_subscriptions = short_boards |> Enum.map(& &1.id) |> MapSet.new()
    orig_subscriptions = socket.assigns.subscriptions

    Enum.each(MapSet.difference(orig_subscriptions, new_subscriptions), fn id ->
      Lucidboard.unsubscribe("short_board:#{id}")
    end)

    Enum.each(MapSet.difference(new_subscriptions, orig_subscriptions), fn id ->
      Lucidboard.subscribe("short_board:#{id}")
    end)

    assign(socket,
      short_boards: short_boards,
      board_pagination: board_pagination,
      subscriptions: new_subscriptions,
      search_key: search_key,
      boards_filter: boards_filter
    )
  end

  defp get_page_number(%{assigns: %{board_pagination: %{page_number: num}}}),
    do: num

  defp get_page_number(_), do: nil
end

lib/lucidboard_web/views/dashboard_view.ex
defmodule LucidboardWeb.DashboardView do
  use LucidboardWeb, :view
end

lib/lucidboard_web/templates/dashboard/index.html.eex
<div class="o-CenteredColumn">
  <a href="<%= Routes.board_path(@conn, :create) %>"
    class="button is-primary is-outlined is-pulled-right">
    <%= fas("plus") %><span>Create Board</span>
  </a>

  <h2 class="title">All Lucidboards</h2>

  <%= for board <- @boards do %>
    <a class="card is-block c-Card u-Mbm" href="<%= Routes.board_path(@conn, :index, board.id) %>">
      <div class="c-Card__content card-content">
        <div class="content">
          <h3 class="b-Subtitle subtitle is-marginless">
            <%= board.title %>
          </h3>
          Created by <strong><%= board.user.name %></strong>,
          Last updated at <strong><%= board.updated_at %></strong>
        </div>
      </div>
      <%# <footer class="card-footer">
        <a href="#" class="card-footer-item">Settings</a>
      </footer> %>
    </a>
  <% end %>

  <%= if @boards == [] do %>
    <em>No Lucidboards!</em>
  <% end %>
</div>

lib/lucidboard_web/templates/dashboard/index.html.leex
<div class="centered-column u-Pbl">
  <a href="<%= Routes.live_path(LucidboardWeb.Endpoint, LucidboardWeb.CreateBoardLive) %>"
    class="button lb-button is-primary is-outlined is-pulled-right">
    <%= fas("plus") %><span>Create Board</span>
  </a>

  <h2 class="title">Lucidboards</h2>

  <form class="u-Mbl" phx-change="search" id="lb-search">
    <input class="input lb-input lb-input-huge js-search" type="text" name="q" value="<%= @search_key %>" placeholder="Search" />

    <div class="control">
      <label class="radio">
        <input
          type="radio"
          value="all"
          name="boards_filter
          id="radio_all"
          <%= if @boards_filter == "all", do: "checked", else: "" %>
        />
        All Boards
      </label>
      <label class="radio">
        <input
          type="radio"
          value="created"
          name="boards_filter"
          id="radio_created"
          <%= if @boards_filter == "created", do: "checked", else: "" %>
        />
        Your Boards
      </label>
    </div>
  </form>

  <%= for short_board <- @short_boards do %>
    <a class="stack lb-card lb-card--clickable u-Pal u-Mbm"
      href="<%= Routes.live_path(LucidboardWeb.Endpoint, BoardLive, short_board.id) %>">
      <div class="content">
        <h3 class="lb-subtitle subtitle is-marginless stack">
          <%= raw board_access_icon(short_board.access, "lb-icon--fa u-Mrs") %>
          <%= short_board.title %>
        </h3>
          Created by <strong><%= short_board.username %></strong> at
          <span title="<%= utc_to_formatted(short_board.inserted_at, :long) %>">
            <%= utc_to_formatted(short_board.inserted_at, :short) %></span>.
        <%= if short_board.last_event do %>
          <span class="u-Mtm is-block">
          <%= fas("clock") %>
          <%= display_event(short_board.last_event, short_board.anonymous) %>
          </span>
        <% end %>
      </div>
      <%# <footer class="card-footer">
        <a href="#" class="card-footer-item">Settings</a>
      </footer> %>
    </a>
  <% end %>

  <%= if  @board_pagination.total_entries > 0 do %>
    <div class="stack stack--spaceBetween stack--split@m">
      <div class="stack__item">
        <p>
          Showing page <%= @board_pagination.page_number %> of <%= @board_pagination.total_pages %>
        </p>
        <p>
          Total boards: <%= @board_pagination.total_entries %>
        </p>
      </div>
      <div class="stack__item">
        <%= if @board_pagination.page_number > 1 do %>
          <button phx-click="paginate" phx-value="prev" class="button lb-button is-primary">Previous</button>
        <% end %>

        <%= if @board_pagination.page_number < @board_pagination.total_pages do %>
          <button phx-click="paginate" phx-value="next" class="button lb-button is-primary">Next</button>
        <% end %>
      </div>
    </div>
  <% end %>

  <%= if @short_boards == [] do %>
    <em>No Lucidboards!</em>
  <% end %>
</div>