lib/lucidboard_web/router.ex
defmodule LucidboardWeb.Router do
  use LucidboardWeb, :router
  alias LucidboardWeb.LayoutView

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(Phoenix.LiveView.Flash)
    plug(LucidboardWeb.LoadUserPlug)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:put_layout, {LayoutView, :normal})
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/auth", LucidboardWeb do
    pipe_through([:browser])

    get("/:provider", AuthController, :request)
    get("/:provider/callback", AuthController, :callback)
  end

  scope "/", LucidboardWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/changelog", PageController, :changelog)

    get("/signin", UserController, :signin)
    post("/signin", AuthController, :dumb_signin)
    get("/signout", AuthController, :signout)

    get("/user-settings", UserController, :settings)
    post("/user-settings", UserController, :update_settings)

    live("/dashboard", DashboardLive, session: [:user_id])
    live("/create-board", CreateBoardLive, session: [:path_params, :user_id])

    live("/boards", DashboardLive, session: [:user_id])
    live("/boards/:id", BoardLive, session: [:path_params, :user_id])

    post("/boards/:id/dnd-into-junction", BoardController, :dnd_into_junction)
    post("/boards/:id/dnd-into-pile", BoardController, :dnd_into_pile)
  end
end

lib/lucidboard_web/views/layout_view.ex
defmodule LucidboardWeb.LayoutView do
  use LucidboardWeb, :view

  @doc "Render our outer-most wrapping"
  def render_layout(outer_layout, assigns, do: content) do
    render(outer_layout, Map.put(assigns, :inner_layout, content))
  end

  defp body_class(nil), do: "t-light"
  defp body_class(%{settings: %{theme: theme}}), do: "t-#{theme}"
end

lib/lucidboard_web/templates/layout/full_width.html.eex
<%= render_layout "app.html", assigns do %>
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= render @view_module, @view_template, assigns %>
<% end %>

lib/lucidboard_web/templates/layout/header_user_menu.html.eex
<div id="usermenu" class="dropdown lb-dropdown is-hoverable is-right u-Width--100">
  <div class="dropdown-trigger lb-dropdown-trigger">
    <button class="lb-dropdown-button" aria-haspopup="true" aria-controls="dropdown-menu">
      <%= avatar(@user) %>
      <span><%= @user.name %></span>
      <%= fas("angle-down", "is-small") %>
    </button>
  </div>
  <div class="dropdown-menu lb-dropdown-menu" id="dropdown-menu" role="menu">
    <div class="dropdown-content lb-dropdown-content">
      <a href="<%= Routes.user_path(@conn, :settings) %>" class="dropdown-item lb-dropdown-item">
        Settings
      </a>
      <a href="<%= Routes.auth_path(@conn, :signout) %>" class="dropdown-item lb-dropdown-item">
        Sign Out
      </a>
    </div>
  </div>
</div>

lib/lucidboard_web/templates/layout/normal.html.eex
<%= render_layout "app.html", assigns do %>
  <main role="main" class="u-Ptl u-Phm">
    <div class="centered-column">
      <p class="alert alert-info u-Mbm" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    </div>
    <%= render @view_module, @view_template, assigns %>
  </main>
<% end %>